# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4dfc929d3631cc4429afb5b61765fc9dd50a3d76d432dc056f53e7ed8db0ba1d706504b8432cbc17297b75489de61c15ec510b40fe1e8d9ab7732b7290f5386

test:
  secret_key_base: dd5503e2253a0a2a90edaea060fa083592ee452b1b0c1098248e47bacfd4b10185512ce00a627eabfdf4d2fded5dfd44fc8adf11a16d682d3ce96bfb0b4fb075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
